# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7850aec83b3eb1abe9fe507965c8a732a28d49916bd308ce150b77814251e4a583d17fa4e87adb6990d817b0ab66296b46fc4512e8e8aa2151a9957db81a57

test:
  secret_key_base: 5f6daea97ecf313ddd8cb613d8afe51b298ee322c6530baaf745045ad55c46238cce209df0ce1373e2f04f1d3237d2bdc95f4c5a4f709e8609be52b472e15697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
